/**
 * iHack.AUDIO Neural Backup Suite
 * Leverages client-side IndexedDB to store audio Blobs / Files and associated
 * session state metadata so that a page reload or unexpected crash does not format
 * the costly synthesized files generated by Gemini.
 */

const DB_NAME = 'iHackAudioBackupDB';
const DB_VERSION = 1;
const STORE_NAME = 'audio_backups';

export interface BackupMetadata {
  podcastContext: string;
  scene: string;
  context: string;
  singleSpeakerNote: string;
  speaker1Note: string;
  speaker2Note: string;
  directorNote: string;
  podcastMode: 'SINGLE' | 'MULTI';
  scriptText: string;
  prodResult: any | null;
  timestamp: number;
}

// Open / initialize IndexedDB
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onerror = () => {
      console.error('Failed to open backup database.');
      reject(request.error);
    };

    request.onsuccess = () => {
      resolve(request.result);
    };

    request.onupgradeneeded = (event: any) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
  });
}

/**
 * Saves a binary blob to the IndexedDB cache
 */
export async function saveAudioToBackup(key: 'generatedAudio' | 'masteredAudio', blob: Blob | null): Promise<void> {
  if (!blob) {
    // If null, delete the entry
    await deleteBackupByKey(key);
    return;
  }
  
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readwrite');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.put(blob, key);

      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error(`Error backup saving ${key}:`, error);
  }
}

/**
 * Saves metadata checklist details
 */
export async function saveMetadataToBackup(metadata: BackupMetadata): Promise<void> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readwrite');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.put(metadata, 'metadata');

      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error('Error saving backup metadata:', error);
  }
}

/**
 * Retrieves a saved audio blob or metadata
 */
export async function getBackupByKey<T>(key: 'generatedAudio' | 'masteredAudio' | 'metadata'): Promise<T | null> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readonly');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.get(key);

      request.onsuccess = () => {
        resolve((request.result as T) || null);
      };
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error(`Error retrieving backup for ${key}:`, error);
    return null;
  }
}

/**
 * Deletes backup by key
 */
export async function deleteBackupByKey(key: 'generatedAudio' | 'masteredAudio' | 'metadata'): Promise<void> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readwrite');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.delete(key);

      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error(`Error deleting backup item '${key}':`, error);
  }
}

/**
 * Completely clears the local cache/backup database
 */
export async function wipeBackupSuite(): Promise<void> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readwrite');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.clear();

      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error('Error clearing backup database:', error);
  }
}
